### ISSUE TITLE
Value error during training

### ISSUE THREAD

**Issue by briancantwe** [RongLiu-Leo/AtomGS#1]
Hello!  Nice work, I'm excited try it out.   Installed and tried a test on some colmap data I've used with 3dgs, but I get this error during training.  Any ideas?   Thanks!

(atomgs) C:\Users\main\Documents\Github\AtomGS>python train.py -s colmap_export
Optimizing
Output folder: ./output/0000000168 [22/05 17:17:51]
Tensorboard not available: not logging progress [22/05 17:17:51]
Reading camera 73/73 [22/05 17:17:55]
Loading Training Cameras [22/05 17:17:55]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [22/05 17:17:55]
Loading Test Cameras [22/05 17:19:41]
Number of points at initialisation :  91413 [22/05 17:19:41]
Training progress:   0%|                                                                     | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\main\Documents\Github\AtomGS\train.py", line 230, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, render_items)
  File "C:\Users\main\Documents\Github\AtomGS\train.py", line 70, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\main\Documents\Github\AtomGS\gaussian_renderer\__init__.py", line 85, in render
    rendered_image, rendered_depth, rendered_median_depth, rendered_alpha, radii = rasterizer(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 2)
Training progress:   0%|                                                                     | 0/30000 [00:00<?, ?it/s]

(atomgs) C:\Users\main\Documents\Github\AtomGS>

**Comment by RongLiu-Leo** [comment]
The code was just released now. So the previous version may have some minor problems
Reclone one and have a try.

For your provided code, I think your code is misusing our updated Cuda rasterizer and the original 3DGS rasterizer.

Original:
rendered_image, radii = rasterizer()
Ours:
rendered_image, rendered_depth, rendered_median_depth, rendered_alpha, radii = rasterizer()

Leads to the mismatch ValueError: not enough values to unpack (expected 5, got 2).

**Comment by briancantwe** [comment]
Thank you, all fixed now.
