### ISSUE TITLE
GPU Memory requirements

### ISSUE THREAD

**Issue by briancantwe** [RongLiu-Leo/AtomGS#2]
Hello again!

What are the GPU requirements for AtomGS?  I'm using a 24GB GPU and trying 51 images at 800x res, but it spikes to 24GB of memory used at 2% of training, then crashes.

**Comment by RongLiu-Leo** [comment]
It really depends on your input dataset.
By default, it is 7000. You can gradually decrease it, like 3500, 1750, ..., to see which one fit your data best.

**Comment by briancantwe** [comment]
Hmm.  I tried with several different options, all the way down to 1, but I still get a crash by 900 iterations.  Even moved over to a 48GB GPU, but still no good.

**Comment by RongLiu-Leo** [comment]
Then try to increase the hyper parameter 
--atom_init_quantile 0.01
By default, it is 0.01, the first percentile. This parameter controls the "resolution" of fine details. Hence a lower one may work for your case.

**Comment by briancantwe** [comment]
Thanks for the suggestion.   Tried going up and down (as I wasn't sure
which way you meant) but I still can't get past 3% before crashing.

**Comment by RongLiu-Leo** [comment]
My bad.
It should be "a higher one".

**Comment by RongLiu-Leo** [comment]
We used the same datasets and evaluation code from 3DGS. 

May check [this](https://github.com/graphdeco-inria/gaussian-splatting/pull/14). 
Set --data_device cpu to put data on CPU to save VRAM for training.
